// LeetCode #389. Find the Difference
/* Instructions
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"
*/

// Solution
const findTheDifference = function(s, t) {
    const mapS = {}
    const mapT = {}

    for (const char of s) {
        mapS[char] = mapS[char] + 1 || 1
    }

    for (const char of t) {
        mapT[char] = mapT[char] + 1 || 1
    }

    for (const key in mapT) {
        if (mapT[key] != mapS[key]) {
            return key
        }
    }
}

// Explanation
// Instantiate an empty object to hold our map of the string, s
// Instantiate an empty object to hold our map of the string, t
// Loop through both s and t, adding a property with each character with a value of +1 for every time it occurs
// Then, check each property in mapT and check if it is not equal to that of mapS, and if so, that is the difference, so return that key.
